[2025-07-20T15:56:49.292+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Pipeline.bronze_transform manual__2025-07-20T15:56:35.930090+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
